language: go
go:
          - 1.8
          - 1.9
          - master
os:
          - linux
          - osx
before_script:
          - cd exclamation
          - make dep-install
          - make dep
          - cd ..
          - cd jgob
          - make dep
          - cd ..
sudo: required

script: cd jgob && make && cd ../ && cd exclamation && make
