language: go
        - 1.5
        - 1.6
        - 1.7
        - 1.8
        - 1.9
        - master
before_script:
          - go get "github.com/BurntSushi/toml"
          - go get "github.com/osrg/gobgp/api"
          - go get "github.com/osrg/gobgp/config"
          - go get "github.com/osrg/gobgp/gobgp/cmd"
          - go get "github.com/osrg/gobgp/packet/bgp"
          - go get "github.com/osrg/gobgp/server"
          - go get "github.com/osrg/gobgp/table"
          - go get "github.com/satori/go.uuid"
          - go get "github.com/sirupsen/logrus"
          - go get "github.com/sirupsen/logrus/hooks/syslog"
          - go get "google.golang.org/grpc"
          - go get "github.com/gorilla/mux"
          - go get "github.com/joho/godotenv"
          - go get "github.com/ajays20078/go-http-logger"
          - jgob/makeSSL.sh
          - exclamation/makeSSL.sh
sudo: required

script: cd jgob && go build && cd ../ && cd exclamation && go build 
